### ISSUE TITLE
Fails to import correctly on RedHat Linux

### ISSUE THREAD

**Issue by ryanpepper** [conda-forge/fenics-feedstock#35]
Tried installing on our compute cluster at the University of Southampton, installs fine but when trying to import in Python
```
>>> import fenics
Traceback (most recent call last):
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/dolfin/cpp/common.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: libumfpack.so.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/scratch/rp20g15/anaconda/envs/py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_common'
```

**Comment by ryanpepper** [comment]
(This is using Python 3.5.2)

**Comment by minrk** [comment]
What do you see in `conda list` and `ls /scratch/rp20g15/anaconda/envs/py35/lib/libumf*`?

**Comment by ryanpepper** [comment]
Apologies it's taken me so long to get back to you.

I've got no idea why, but it's started working now. I tried logging in / out again at the time, but for some reason it's importing and running correctly.

Thanks for writing the Conda package by the way, it's much easier for me to use FEniCs with this than through Docker and has made a big difference to my workflow.
