### ISSUE TITLE
Errors after installing FEniCS

### ISSUE THREAD

**Issue by sophia-wright-blue** [conda-forge/fenics-feedstock#50]
Hello, this issue has been raised before, i looked through the previous posts, but could not figure out the solution. I tried installing a previous verison of fenics, and that did not work, and installed the latest version again, and i get the following error, 

```

from fenics import *

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/fenics/__init__.py", line 7, in <module>

    from dolfin import *

  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>

    from . import cpp

  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>

    exec("from . import %s" % module_name)

  File "<string>", line 1, in <module>

  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/dolfin/cpp/common.py", line 21, in <module>

    _common = swig_import_helper()

  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper

    return importlib.import_module('_common')

  File "/Users/sophiaw/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module

    __import__(name)

ImportError: No module named _common

```

Any help to fix this would be greatly appreciated - Thank you.

**Comment by sophia-wright-blue** [comment]
I'm able to run fenics now. I removed anaconda and reinstalled it using the command line installer. on doing import dolfin, i then got the same error: RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

 I upgraded fenics using conda upgrade fenics numpy, and now fenics works fine.

 Not sure what i did wrong earlier! Thank you to MinRK for his help.
