### ISSUE TITLE
 version `GLIBCXX_3.4.21' not found (required by /lib64/libboost_timer.so.1.64.0);

### ISSUE THREAD

**Issue by Ace-** [conda-forge/fenics-feedstock#57]
System: Fedora 27
Installation method: Anaconda

The error arises when running any FEniCS python sample file. 
```
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
--- Instant: compiling ---
In instant.import_module_directly: Failed to import module 'dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b' from '/tmp/instant/cache/dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b';
ImportError:/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/cpp/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib64/libboost_timer.so.1.64.0);
Failed to import module found in cache. Modulename: 'dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b';
Path: '/tmp/instant/cache/dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b';
ImportError:/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/cpp/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib64/libboost_timer.so.1.64.0);
Traceback (most recent call last):
  File "test_fenics.py", line 20, in <module>
    u_D = Expression('1 + x[0]*x[0] + 2*x[1]*x[1]', degree=2)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/functions/expression.py", line 679, in __new__
    mpi_comm=kwargs.get("mpi_comm"))
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/compilemodules/expressions.py", line 266, in compile_expressions
    mpi_comm=mpi_comm)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/compilemodules/expressions.py", line 183, in compile_expression_code
    mpi_comm=mpi_comm)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/compilemodules/jit.py", line 70, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/compilemodules/compilemodule.py", line 603, in compile_extension_module
    **instant_kwargs)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/instant/build.py", line 586, in build_module
    module = import_and_cache_module(module_path, modulename, moduleids)
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/instant/cache.py", line 92, in import_and_cache_module
    e))
  File "/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/instant/output.py", line 103, in instant_assert
    raise AssertionError(text)
AssertionError: Failed to import module found in cache. Modulename: 'dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b';
Path: '/tmp/instant/cache/dolfin_dc17a5b57a6ee029129b3fd1d8b0dac5cc49a70b';
ImportError:/home/user/anaconda3/envs/fenicsproject-py36/lib/python3.6/site-packages/dolfin/cpp/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib64/libboost_timer.so.1.64.0);
Aborted (core dumped)
```

**Comment by minrk** [comment]
What's `conda list`?

**Comment by Ace-** [comment]
[condalist.txt](https://github.com/conda-forge/fenics-feedstock/files/1700544/condalist.txt)
Packages in the FEniCS env are listed in the attachment.

**Comment by peterwoerner** [comment]
I get a similar error on my hpc server: CentOS Linux release 7.3.1611 (Core)

```
 In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/panfs/s
torage.local/home-4/pcw13/.conda/envs/fenicsproject/.cache/instant/error/dolfin_54c0e00d2f3f781e51
a2c637668bef046e436b0c/compile.log'
     Traceback (most recent call last):
       File "getMechanicalResponse.py", line 17, in <module>
         (transverseLoad, initPosR, initPosZ, finalPosr, finalPosz) = membrane.VHB(params, prestre
tch, -displacement, voltage, options)
       File "/panfs/storage.local/home-4/pcw13/wei/VHB_inhomogeneous_model_FEniCS_DRAM/membrane_1d
_v15.py", line 181, in VHB
         u_init = Expression(('x[0]*prestretch-x[0]', '(za-ZA)*(rb-x[0]*prestretch)/(rb-ra)'), pre
stretch=prestretch, ra=ra, rb=rb, za=za, ZA=ZA, degree=2)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packag
es/dolfin/functions/expression.py", line 679, in __new__
         mpi_comm=kwargs.get("mpi_comm"))
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packag
es/dolfin/compilemodules/expressions.py", line 266, in compile_expressions
         mpi_comm=mpi_comm)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packag
es/dolfin/compilemodules/expressions.py", line 183, in compile_expression_code
         mpi_comm=mpi_comm)
File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packag
es/dolfin/compilemodules/expressions.py", line 266, in compile_expressions
         mpi_comm=mpi_comm)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packag
es/dolfin/compilemodules/expressions.py", line 183, in compile_expression_code
         mpi_comm=mpi_comm)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packages/dolfin/compilemodules/jit.py", line 70, in mpi_jit
         return local_jit(*args, **kwargs)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packages/dolfin/compilemodules/compilemodule.py", line 603, in compile_extension_module
         **instant_kwargs)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packages/instant/build.py", line 577, in build_module
         build_system)
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packages/instant/build.py", line 170, in recompile
         instant_error(msg % (cmd, compile_log_filename_dest))
       File "/panfs/storage.local/home-4/pcw13/.conda/envs/fenicsproject/lib/python2.7/site-packages/instant/output.py", line 96, in instant_error
         raise RuntimeError(text)
     RuntimeError: In instant.recompile: The module did not compile with command 'make VERBOSE=1',
```

**Comment by jan-janssen** [comment]
This should be fixed now, otherwise feel free to open a new issue.
