### ISSUE TITLE
Fenics ImportError: No module named _common

### ISSUE THREAD

**Issue by WilliamPJSmith** [conda-forge/fenics-feedstock#70]
Issue:

I am trying to install fenics into an existing conda environment. I can install fenics without problems, but when I try to import it from within the environment, I get an error message: 

> No module named _common.

My environment is [cellmodeller](http://haselofflab.github.io/CellModeller/):
```
$ conda info --envs
# conda environments:
#
base                  *  /Users/user/anaconda2
cellmodeller             /Users/user/anaconda2/envs/cellmodeller
```
I installed fenics using
```
conda install --name cellmodeller -c conda-forge fenics
```
which gave no errors.
However, when I try to import fenics from within my cellmodeller environment, I get the following error message:

```
./anaconda2/envs/cellmodeller/bin/python2.7 -c 'from fenics import *'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/Users/user/anaconda2/envs/cellmodeller/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _common
```
Does anyone have any ideas? I've seen similar errors listed before [here](https://groups.google.com/forum/#!topic/fenics-support/yrseUpq3PSA) and [here](https://github.com/conda-forge/fenics-feedstock/issues/15). In the latter case, it was suggested that reverting boost version would solve the problem. I tried this using

```
conda install --name cellmodeller -c conda-forge boost=1.61
```
which ran successfully, but I still get a similar error when trying to import fenics as above.
Can anyone help?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

packages in environment at /Users/user/anaconda2:
_ipyw_jlab_nb_ext_conf    0.1.0            py27h172cb35_0  
alabaster                 0.7.10           py27h9dd7d6e_0  
anaconda                  custom           py27h2cfa9e9_0    anaconda
anaconda-client           1.6.5            py27hc13fba8_0  
anaconda-navigator        1.6.9            py27h103b016_0  
anaconda-project          0.8.0            py27h9e3d455_0  
appnope                   0.1.0            py27hb466136_0  
appscript                 1.0.1            py27h451298e_1  
asn1crypto                0.22.0           py27h61af4a7_1  
astroid                   1.5.3            py27h96f3fd4_0  
astropy                   2.0.2            py27h87cc2bd_4  
babel                     2.5.0            py27h7311c9e_0  
backports                 1.0              py27hb4f9756_1  
backports.functools_lru_cache 1.4              py27h2aca819_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
beautifulsoup4            4.6.0            py27h9416283_1  
bitarray                  0.8.1            py27hd5bfd95_0  
bkcharts                  0.2              py27haafc882_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3           py27hb49378a_0  
bleach                    2.0.0            py27ha7d1710_0  
bokeh                     0.12.10          py27hf91827b_0  
boost                     1.66.0                   py27_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
boto                      2.48.0           py27hacdd0fd_1  
bottleneck                1.2.1            py27h71f98a3_0  
bzip2                     1.0.6                h92991f9_1  
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cdecimal                  2.3              py27hf5d9fd9_1  
certifi                   2018.10.15            py27_1000    conda-forge
cffi                      1.10.0           py27haac214c_1  
chardet                   3.0.4            py27h2842e91_1  
click                     6.7              py27h2b86a94_0  
cloudpickle               0.4.0            py27h665dddb_0  
clyent                    1.2.2            py27hc0ae608_0  
cmake                     3.9.4                h30c3106_0  
colorama                  0.3.9            py27hbbe92b6_0  
conda                     4.4.7                    py27_0    anaconda
conda-build               3.0.27           py27h7659b69_0  
conda-env                 2.6.0                h36134e3_0    anaconda
conda-verify              2.0.0            py27hbebe81d_0  
configparser              3.5.0            py27hc7edf1b_0  
contextlib2               0.5.5            py27h9cb85f4_0  
cryptography              2.0.3            py27hab69567_1  
curl                      7.55.1               h7601780_3  
cycler                    0.10.0           py27hfc73c78_0  
cython                    0.26.1           py27h6a053f9_0  
cytoolz                   0.8.2            py27ha56cda1_0  
dask                      0.15.3           py27h8a1b457_0  
dask-core                 0.15.3           py27h6a32bf4_0  
datashape                 0.5.4            py27hd6a1745_0  
dbus                      1.10.22              h50d9ad6_0  
decorator                 4.1.2            py27h9f877ea_0  
distributed               1.19.1           py27h67dd2ec_0  
docutils                  0.14             py27h0befae3_0  
eigen                     3.3.5                h2d50403_1    conda-forge
entrypoints               0.2.3            py27hd680fb1_2  
enum34                    1.1.6            py27hf475452_1  
et_xmlfile                1.0.1            py27hc42f929_0  
expat                     2.2.4                h8f26bf8_1  
fastcache                 1.0.2            py27hc4635c7_0  
fenics                    2017.2.0            np113py27_3    conda-forge
filelock                  2.0.12           py27h72fe922_0  
flask                     0.12.2           py27h3ac5568_0  
flask-cors                3.0.3            py27h13db576_0  
freetype                  2.8                  h143eb01_0  
funcsigs                  1.0.2            py27hb9f6266_0  
functools32               3.2.3.2          py27h8ceab06_1  
futures                   3.1.1            py27hb02a37a_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             hb0f4f8b_2  
gevent                    1.2.2            py27hc02608c_0  
glib                      2.53.6               ha08cb78_1  
glob2                     0.5              py27h2f8fe13_0  
gmp                       6.1.2                h4a9834d_0  
gmpy2                     2.0.8            py27h7e2fca4_1  
greenlet                  0.4.12           py27h081ed54_0  
grin                      1.2.1            py27hc43e5f3_1  
h5py                      2.7.0            py27h217cc45_1  
hdf5                      1.10.1               h6090a45_0  
heapdict                  1.0.0            py27hb5e74ad_0  
html5lib                  0.999999999      py27hec7e2bc_0  
hypre                     2.11.2                        1    conda-forge
icu                       58.2                 hea21ae5_0  
idna                      2.6              py27hedea723_1  
imageio                   2.2.0            py27h37746d9_0  
imagesize                 0.7.1            py27h4f7bcc8_0  
intel-openmp              2018.0.0             h68bdfb3_7  
ipaddress                 1.0.18           py27h5b9a5b9_0  
ipykernel                 4.6.1            py27h1e70a78_0  
ipython                   5.4.1            py27h2b3d779_1  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.0.0            py27h3e52029_0  
isort                     4.2.15           py27h5bf637f_0  
itsdangerous              0.24             py27h3948ded_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.3              py27hfeaf94f_0  
jedi                      0.10.2           py27hbb5dc62_0  
jinja2                    2.9.6            py27h92590e2_1  
jpeg                      9b                   haccd157_1  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0            py27hec63c99_0  
jupyter_client            5.1.0            py27hfaf569a_0  
jupyter_console           5.2.0            py27h9702a86_1  
jupyter_core              4.3.0            py27hd5161ba_0  
jupyterlab                0.27.0           py27h25d4955_2  
jupyterlab_launcher       0.4.0            py27he518b91_0  
lazy-object-proxy         1.3.1            py27h712ce3f_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                hd939716_3  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 h99df5da_5  
libpng                    1.6.32               hce72d48_2  
libsodium                 1.0.13               hba5e272_2  
libssh2                   1.8.0                h1218725_2  
libtiff                   4.0.8                h8cd0352_9  
libuv                     1.23.2               h470a237_0    conda-forge
libxml2                   2.9.4                hbd0960b_5  
libxslt                   1.1.29               h95a2935_5  
llvmlite                  0.20.0                   py27_0  
locket                    0.2.0            py27ha10513d_1  
lxml                      4.1.0            py27hcb5f3a6_0  
lzo                       2.10                 hb6b8854_1  
markupsafe                1.0              py27hd3c86fa_1  
matplotlib                2.1.0            py27h3078195_0  
mccabe                    0.6.1            py27h1f69e8d_0  
metis                     5.1.0                h470a237_3    conda-forge
mistune                   0.7.4            py27h1658d75_0  
mkl                       2018.0.0             h5ef208c_6  
mkl-service               1.1.2            py27hcba3029_4  
mpc                       1.0.3                hc455b36_4  
mpfr                      3.1.5                h7fa3772_1  
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_5    conda-forge
mpmath                    0.19             py27h09cdc99_2  
msgpack-python            0.4.8            py27h635ded4_0  
multipledispatch          0.4.9            py27h10993aa_0  
mumps-mpi                 5.0.2           blas_openblas_0  [blas_openblas]  conda-forge
navigator-updater         0.1.0            py27ha63e0b4_0  
nbconvert                 5.3.1            py27h6455e4c_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.0                  ha932d30_1  
networkx                  2.0              py27h2503496_0  
nltk                      3.2.4            py27h1626047_0  
nose                      1.3.7            py27h2ee3cb8_2  
notebook                  5.0.0            py27h5f5981d_2  
numba                     0.35.0              np113py27_6  
numexpr                   2.6.2            py27h99e4b4f_1  
numpy                     1.13.3          py27_blas_openblas_201  [blas_openblas]  conda-forge
numpydoc                  0.7.0            py27h022f19e_0  
odo                       0.5.1            py27h992a9f7_0  
olefile                   0.44             py27h73ba740_0  
openblas                  0.2.20                        8    conda-forge
openpyxl                  2.4.8            py27h70e7ed9_1  
openssl                   1.0.2p               h470a237_1    conda-forge
packaging                 16.8             py27h24b219a_0  
pandas                    0.20.3           py27h2a3d8ca_2  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py27hed78c4e_1  
parmetis                  4.0.3                hf73f2d4_2    conda-forge
partd                     0.3.8            py27h7560dbf_0  
path.py                   10.3.1           py27h5e25276_0  
pathlib2                  2.3.0            py27he09da1e_0  
patsy                     0.4.1            py27h40ed276_0  
pcre                      8.41                 h29eefc5_0  
pep8                      1.7.0            py27hff3397c_0  
petsc                     3.8.4           blas_openblas_0  [blas_openblas]  conda-forge
petsc4py                  3.8.1                    py27_1    conda-forge
pexpect                   4.2.1            py27hc4e4961_0  
pickleshare               0.7.4            py27h37e3d41_0  
pillow                    4.2.1            py27h2cf1d5f_0  
pip                       9.0.1            py27h61def0c_3  
pkg-config                0.29.2               hf837533_3    conda-forge
pkginfo                   1.4.1            py27ha9221e7_0  
ply                       3.10             py27h6279b8a_0  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
psutil                    5.4.0            py27h7076ac6_0  
ptscotch                  6.0.4                         2    conda-forge
ptyprocess                0.5.2            py27h70f6364_0  
py                        1.4.34           py27h917aa57_1  
pyaudio                   0.2.7            py27h3777516_1  
pycodestyle               2.3.1            py27h5b634e0_0  
pycosat                   0.6.3            py27h6c51c7e_0    anaconda
pycparser                 2.18             py27h0d28d88_1  
pycrypto                  2.6.1            py27h4efa152_1  
pycurl                    7.43.0           py27h398a7fe_3  
pyflakes                  1.6.0            py27h4446e76_0  
pygments                  2.2.0            py27h1a556bb_0  
pylint                    1.7.4            py27hc678664_0  
pyodbc                    4.0.17           py27hc9de18c_0  
pyopenssl                 17.2.0           py27h732fe57_0  
pyparsing                 2.2.0            py27h5bb6aaf_0  
pyqt                      5.6.0            py27hf21fe59_6  
pysocks                   1.6.7            py27h1cff6a6_1  
pytables                  3.4.2            py27ha4551b8_2  
pytest                    3.2.1            py27h173df03_1  
python                    2.7.14              he768d2d_19  
python-dateutil           2.6.1            py27hd56c96b_1  
python.app                2                py27h84f57d0_6  
pytz                      2017.2           py27hb891d23_1  
pywavelets                0.5.2            py27hd99e88a_0  
pyyaml                    3.12             py27ha7932d0_1  
pyzmq                     16.0.2           py27he61c07e_2  
qt                        5.6.2               h9975529_14  
qtawesome                 0.4.4            py27hdeb2f59_0  
qtconsole                 4.3.1            py27hdc90b4f_0  
qtpy                      1.3.1            py27h39159f8_0  
readline                  7.0                  h81b24a6_3  
requests                  2.18.4           py27h9b2b37c_1  
rhash                     1.3.6                h470a237_1    conda-forge
rope                      0.10.5           py27he855d02_0  
ruamel_yaml               0.11.14          py27h31666c4_2  
scalapack                 2.0.2                h186ce0b_3    conda-forge
scandir                   1.6              py27h97aa1ee_0  
scikit-image              0.13.0           py27h03e84e1_1  
scikit-learn              0.19.1           py27h9788993_0  
scipy                     0.19.1           py27hf01dd8f_3  
seaborn                   0.8.0            py27h92884e4_0  
setuptools                36.5.0           py27h2a45cec_0  
simplegeneric             0.8.1            py27h6db5e31_0  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.18.1           py27h6300f65_2  
six                       1.11.0           py27h7252ba3_1  
slepc                     3.8.3           blas_openblas_0  [blas_openblas]  conda-forge
slepc4py                  3.8.0                    py27_0    conda-forge
snowballstemmer           1.2.1            py27h68ac032_0  
sortedcollections         0.5.3            py27h8094be4_0  
sortedcontainers          1.5.7            py27h322dbbf_0  
sphinx                    1.6.3            py27h11269f0_0  
sphinxcontrib             1.0              py27hd2ed746_1  
sphinxcontrib-websupport  1.0.1            py27h857890b_1  
spyder                    3.2.4            py27h93d9c3e_0  
sqlalchemy                1.1.13           py27hcbc9ed3_0  
sqlite                    3.20.1               h900c3b0_1  
ssl_match_hostname        3.5.0.1          py27h8780752_2  
statsmodels               0.8.0            py27h6d68dbf_0  
subprocess32              3.2.7            py27h24b2887_0  
suitesparse               4.5.4           blas_openblas_201  [blas_openblas]  conda-forge
swig                      3.0.12               hfc679d8_3    conda-forge
sympy                     1.1.1            py27hce55102_0  
tbb                       2019.1               h2d50403_0    conda-forge
tblib                     1.3.2            py27ha684fc4_0  
terminado                 0.6              py27he40bf16_0  
testpath                  0.3.1            py27h72d81a5_0  
tk                        8.6.7                hcdce994_1  
toolz                     0.8.2            py27h27228c4_0  
tornado                   4.5.2            py27h29aec9e_0  
traitlets                 4.3.2            py27hcf08151_0  
typing                    3.6.2            py27h646fea0_0  
unicodecsv                0.14.1           py27h170f95c_0  
unixodbc                  2.3.4                h4cb4dde_1  
urllib3                   1.22             py27hc3787e9_0  
vtk                       6.3.0                    py27_1    anaconda
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1            py27h19a9f58_1  
werkzeug                  0.12.2           py27hcac71f8_0  
wheel                     0.29.0           py27h84bd1c0_1  
widgetsnbextension        3.0.2            py27h56f70de_1  
wrapt                     1.10.11          py27hd341262_0  
xlrd                      1.1.0            py27hbd41ed1_1  
xlsxwriter                1.0.2            py27h7f1064a_0  
xlwings                   0.11.4           py27h4d78f01_0  
xlwt                      1.2.0            py27hbeec4ae_0  
xz                        5.2.3                ha24016e_1  
yaml                      0.1.7                hff548bb_1  
zeromq                    4.2.2                h131e0f7_1  
zict                      0.1.3            py27h5fff8b1_0  
zlib                      1.2.11               h60db283_1  
zoo-wsmithpro:~ user$ 

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 4.4.7
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       base environment : /Users/user/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/user/anaconda2/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/anaconda2/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by WilliamPJSmith** [comment]
Hi minrk,

Thanks for your speedy response!
I've just tried your suggestion by running
```
$ conda install --name cellmodeller -c conda-forge fenics==2018.1.0
```
but this gives the error
```
Solving environment: / failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34
  - fenics==2018.1.0 -> petsc4py[version='>=3.9.1,<3.10.0a0'] -> petsc=3.9 -> mumps-mpi[version='>=5.1.2,<5.2.0a0'] -> *[track_features=blas_openblas]
Use "conda info <package>" to see the dependencies for each package.

```
The same thing happens if I revert boost to the original version (1.63):
```
$ conda install --name cellmodeller -c conda-forge boost=1.63
$ conda list -n cellmodeller boost
# packages in environment at /Users/user/anaconda2/envs/cellmodeller:
#
boost                     1.63.0                   py27_5    conda-forge
boost-cpp                 1.63.0                        1    conda-forge

$ conda install --name cellmodeller -c conda-forge fenics==2018.1.0
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - boost=1.63
  - fenics==2018.1.0 -> boost[version='>=1.67.0,<1.67.1.0a0'] -> boost-cpp=1.67.0
Use "conda info <package>" to see the dependencies for each package.
```
Any ideas on how to resolve the dependency conflict?
Many thanks!

**Comment by minrk** [comment]
Try explicitly installing the required version of boost:

    conda install boost=1.67

**Comment by WilliamPJSmith** [comment]
Hi minrk,

I've just tried this using 
```
conda install --name cellmodeller boost=1.67
```
but this is still unsatisfiable:
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - boost=1.67
  - fenics -> boost=1.61
Use "conda info <package>" to see the dependencies for each package.
```
I've also tried removing fenics and then reinstalling the 2018.1.0 release you recommended:

```
$ conda remove --name cellmodeller fenics
...
The following packages will be REMOVED:

    fenics:          2016.1.0-py27_2       conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge --> 2018.03.07-0     
    certifi:         2018.10.15-py27_1000  conda-forge --> 2018.10.15-py27_0
    openssl:         1.0.2p-h470a237_1     conda-forge --> 1.0.2p-h1de35cc_0

$ conda install --name cellmodeller -c conda-forge fenics==2018.1.0
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - decorator
  - fenics==2018.1.0 -> petsc4py[version='>=3.9.1,<3.10.0a0'] -> petsc[version='>=3.9.2,<3.10.0a0'] -> mumps-mpi[version='>=5.1.2,<5.2.0a0'] -> *[track_features=blas_openblas]
Use "conda info <package>" to see the dependencies for each package.
```
This shows a conflict with the package decorator, on which my program cellmodeller depends:
```
$ conda remove --name cellmodeller 'decorator'
...
## Package Plan ##

  environment location: /Users/user/anaconda2/envs/cellmodeller

  removed specs: 
    - decorator

The following packages will be REMOVED:

    cellmodeller: 4.2.1-py27h278bea9_0 trudge
    decorator:    4.1.2-py27h9f877ea_0       

Proceed ([y]/n)? n
```
Is there another fenics release, with dependencies pinned, that wouldn't suffer from this clash?

**Comment by minrk** [comment]
conda conflict errors are so often not informative. I found it, and it's in the [cellmodeller package](https://anaconda.org/trudge/cellmodeller/files) (click the `i` next to a package). cellmodeller pins numpy 1.9.2.*, while current fenics requires numpy >= 1.14 (current is 1.15). So cellmodeller must be either rebuilt with a newer numpy if it really does require pinning that tightly, or it should use `>=` pinning for numpy (more likely, given numpy's forward-compatible ABI).

**Comment by WilliamPJSmith** [comment]
Hi minrk,

Sorry for the delayed response and many thanks for checking this out. I will enquire Re: a new build of cellmodeller with improved numpy pinning, and report back.

Very best wishes,

Will

**Comment by CarmenLee111** [comment]
```$ conda install  -c conda-forge fenics==2018.1.0``` works for me.

**Comment by jan-janssen** [comment]
This should be fixed now, otherwise feel free to open a new issue.
