### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++' in miniconda3 image with

### ISSUE THREAD

**Issue by gatoniel** [conda-forge/fenics-feedstock#87]
Issue:
Hi,
I know about the Docker image of fenics and have used it. But I need fenics now in combination with scipy in a newer version. So I thought of installing fenics in the miniconda3 image via this Dockerfile
```
FROM continuumio/miniconda3:4.6.14

RUN ["/bin/bash", "-c", "conda config --add channels conda-forge"]
RUN ["/bin/bash", "-c", "conda install numpy scipy matplotlib pandas scikit-learn"]
RUN ["/bin/bash", "-c", "conda install -v fenics fenics-dijitso fenics-dolfin fenics-ffc fenics-fiat fenics-libdolfin fenics-ufl"]
RUN ["/bin/bash", "-c", "mkdir /home/fenics"]
RUN ["/bin/bash", "-c", "mkdir /home/fenics/shared"]

WORKDIR /home/fenics/shared
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
```
On my local Windows 10 machine this works and my python code is exectued without errors. But when I build an image with this Dockerfile on our Linux server machine I get this error message:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "adv_fit_direct_to_exp.py", line 118, in multip
    result_r = minimizer(error_func_r, bounds)
  File "/opt/conda/lib/python3.7/site-packages/scipy/optimize/_dual_annealing.py", line 631, in dual_annealing
    energy_state.reset(func_wrapper, rand_state, x0)
  File "/opt/conda/lib/python3.7/site-packages/scipy/optimize/_dual_annealing.py", line 174, in reset
    self.current_energy = func_wrapper.fun(self.current_location)
  File "/opt/conda/lib/python3.7/site-packages/scipy/optimize/_dual_annealing.py", line 374, in fun
    return self.func(x, *self.args)
  File "adv_fit_direct_to_exp.py", line 59, in func
    min_r=r[0], num_r=len(r)-1, num_t=len(t)
  File "/home/fenics/shared/biofilm-dye-diffusion/fenics_solver.py", line 53, in solve_pde
    V = FunctionSpace(mesh, 'P', 1)
  File "/opt/conda/lib/python3.7/site-packages/dolfin/function/functionspace.py", line 33, in __init__
    self._init_convenience(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dolfin/function/functionspace.py", line 100, in _init_convenience
    self._init_from_ufl(mesh, element, constrained_domain=constrained_domain)
  File "/opt/conda/lib/python3.7/site-packages/dolfin/function/functionspace.py", line 43, in _init_from_ufl
    mpi_comm=mesh.mpi_comm())
  File "/opt/conda/lib/python3.7/site-packages/dolfin/jit/jit.py", line 47, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dolfin/jit/jit.py", line 97, in ffc_jit
    return ffc.jit(ufl_form, parameters=p)
  File "/opt/conda/lib/python3.7/site-packages/ffc/jitcompiler.py", line 217, in jit
    module = jit_build(ufl_object, module_name, parameters)
  File "/opt/conda/lib/python3.7/site-packages/ffc/jitcompiler.py", line 133, in jit_build
    generate=jit_generate)
  File "/opt/conda/lib/python3.7/site-packages/dijitso/jit.py", line 178, in jit
    params)
  File "/opt/conda/lib/python3.7/site-packages/dijitso/build.py", line 153, in build_shared_library
    status, output = get_status_output(cmd)
  File "/opt/conda/lib/python3.7/site-packages/dijitso/system.py", line 41, in _get_status_output_subprocess
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/opt/conda/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "adv_fit_direct_to_exp.py", line 187, in <module>
    main()
  File "adv_fit_direct_to_exp.py", line 184, in main
    p.map(multip, l)
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'
```

The only difference I found between the two images ist via the <code>conda info</code>. The
windows machine has 

> Linux/4.14.111-boot2docker

while the Linux server machine has

> Linux/4.15.0-50-generic

in the user-agent output. See below for the full output. How can I fix this issue and is this really related to the different user-agents? 
<br/>
Environment (<code>conda list</code>):
<details>
Windows 10 machine

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37h2e261b9_1
chardet                   3.0.4                    py37_1
cmake                     3.14.5               hf94ab9c_0    conda-forge
conda                     4.6.14                   py37_0    conda-forge
cryptography              2.6.1            py37h1ba5d50_0
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.2               h714fa37_1
eigen                     3.3.7             h6bb024c_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fenics                    2019.1.0                 py37_2    conda-forge
fenics-dijitso            2019.1.0                   py_2    conda-forge
fenics-dolfin             2019.1.0         py37h80b64ce_2    conda-forge
fenics-ffc                2019.1.0                   py_2    conda-forge
fenics-fiat               2019.1.0                   py_2    conda-forge
fenics-libdolfin          2019.1.0             h9041177_2    conda-forge
fenics-ufl                2019.1.0                   py_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.0.8           py37hb20f59a_1002    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
hdf5                      1.10.4          mpi_mpich_ha7d0aea_1006    conda-forge
hypre                     2.15.1            hc98498a_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                      py37_0
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.29.1               h516909a_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
matplotlib                3.1.0                    py37_1    conda-forge
matplotlib-base           3.1.0            py37hfd891ef_1    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                ha14ba45_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             hc99cbb1_1010    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mumps-include             5.1.2                      1007    conda-forge
mumps-mpi                 5.1.2             h5bebb2f_1007    conda-forge
ncurses                   6.1                  he6710b0_1
numpy                     1.15.4          py37h8b7e671_1002    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
parmetis                  4.0.3             hb1a587f_1002    conda-forge
pcre                      8.43                 he6710b0_0
petsc                     3.11.1               h624fa55_1    conda-forge
petsc4py                  3.11.0           py37h906564f_0    conda-forge
pip                       19.0.3                   py37_0
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkgconfig                 1.3.1                 py37_1001    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptscotch                  6.0.6             h5a4526e_1002    conda-forge
pybind11                  2.2.4           py37hc9558a2_1001    conda-forge
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pysocks                   1.6.8                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
qt                        5.6.3                h8bf5577_3
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
scalapack                 2.0.2             h2831592_1005    conda-forge
scikit-learn              0.21.2           py37h627018c_0    conda-forge
scipy                     1.3.0            py37h921218d_0    conda-forge
scotch                    6.0.6             h491eb26_1002    conda-forge
setuptools                41.0.0                   py37_0
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                   py37_0
slepc                     3.11.1               h00d104f_0    conda-forge
slepc4py                  3.11.0           py37hce3d510_0    conda-forge
sqlite                    3.27.2               h7b6447c_0
suitesparse               4.5.6             heab0a99_1202    conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.7               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
urllib3                   1.24.1                   py37_0
wheel                     0.33.1                   py37_0
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3

```

Linux machine

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37h2e261b9_1
chardet                   3.0.4                    py37_1
cmake                     3.14.5               hf94ab9c_0    conda-forge
conda                     4.6.14                   py37_0    conda-forge
cryptography              2.6.1            py37h1ba5d50_0
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.2               h714fa37_1
eigen                     3.3.7             h6bb024c_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fenics                    2019.1.0                 py37_1    conda-forge
fenics-dijitso            2019.1.0                   py_2    conda-forge
fenics-dolfin             2019.1.0         py37h1c4d066_1    conda-forge
fenics-ffc                2019.1.0                   py_2    conda-forge
fenics-fiat               2019.1.0                   py_2    conda-forge
fenics-libdolfin          2019.1.0             h370d018_1    conda-forge
fenics-ufl                2019.1.0                   py_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.0.8           py37hb20f59a_1002    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
hdf5                      1.10.4          mpi_mpich_ha7d0aea_1006    conda-forge
hypre                     2.15.1            hc98498a_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                      py37_0
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.29.1               h516909a_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
matplotlib                3.1.0                    py37_1    conda-forge
matplotlib-base           3.1.0            py37hfd891ef_1    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.2                ha14ba45_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.1            py37hf046da1_0    conda-forge
mpich                     3.2.1             hc99cbb1_1010    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mumps-include             5.1.2                      1007    conda-forge
mumps-mpi                 5.1.2             h5bebb2f_1007    conda-forge
ncurses                   6.1                  he6710b0_1
numpy                     1.15.4          py37h8b7e671_1002    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
parmetis                  4.0.3             hb1a587f_1002    conda-forge
pcre                      8.43                 he6710b0_0
petsc                     3.11.1               h624fa55_1    conda-forge
petsc4py                  3.11.0           py37h906564f_0    conda-forge
pip                       19.0.3                   py37_0
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkgconfig                 1.3.1                 py37_1001    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptscotch                  6.0.6             h5a4526e_1002    conda-forge
pybind11                  2.2.4           py37hc9558a2_1001    conda-forge
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pysocks                   1.6.8                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
qt                        5.6.3                h8bf5577_3
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
scalapack                 2.0.2             h2831592_1005    conda-forge
scikit-learn              0.21.2           py37h627018c_0    conda-forge
scipy                     1.3.0            py37h921218d_0    conda-forge
scotch                    6.0.6             h491eb26_1002    conda-forge
setuptools                41.0.0                   py37_0
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                   py37_0
slepc                     3.11.1               h00d104f_0    conda-forge
slepc4py                  3.11.0           py37hce3d510_0    conda-forge
sqlite                    3.27.2               h7b6447c_0
suitesparse               4.5.6             heab0a99_1202    conda-forge
sympy                     1.4                      py37_0    conda-forge
tbb                       2019.7               hc9558a2_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
urllib3                   1.24.1                   py37_0
wheel                     0.33.1                   py37_0
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
Windows 10 machine

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.14.111-boot2docker debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

Linux machine

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-50-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```

</details>

**Comment by minrk** [comment]
Try running `conda activate -n base` to make sure the conda environment is activated (can set things like $CXX)

**Comment by jan-janssen** [comment]
This should be fixed now, otherwise feel free to open a new issue.
