### ISSUE TITLE
ImportError: cannot import name HDF5File for Fenics

### ISSUE THREAD

**Issue by waynezw0618** [conda-forge/fenics-feedstock#88]
Hello I am trying to install fenics in Conda with python2.7. with following error. can anyone help?

Issue:
Traceback (most recent call last):
  File "single_runner.py", line 2, in <module>
    from env import resume_env
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL/baseline_flow/env.py", line 10, in <module>
    from Env2DCylinder import Env2DCylinder
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL/baseline_flow/../Env2DCylinder.py", line 8, in <module>
    from msh_convert import convert
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL/baseline_flow/../msh_convert.py", line 2, in <module>
    from dolfin import Mesh, HDF5File, MeshFunction
ImportError: cannot import name HDF5File

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /anaconda2/envs/fenicsproject:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    py27_0    conda-forge
astor                     0.7.1                      py_0    conda-forge
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   pypi_0    pypi
backports                 1.0                        py_2    conda-forge
backports.weakref         1.0.post1             py27_1000    conda-forge
bleach                    1.5.0                    py27_0    conda-forge
boost                     1.61.0                   py27_2    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
c-ares                    1.15.0            h1de35cc_1001    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_0    conda-forge
cmake                     3.14.5               hdd2e4aa_0    conda-forge
configparser              3.7.4                    pypi_0    pypi
contextlib2               0.5.5                    pypi_0    pypi
curl                      7.64.1               h22ea746_0    conda-forge
dijitso                   2016.1.0                 pypi_0    pypi
eigen                     3.3.7             h04f5b5a_1000    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fastcache                 1.1.0            py27h01d97ff_0    conda-forge
fenics                    2016.1.0                 py27_2    conda-forge
fiat                      2016.1.0                 pypi_0    pypi
funcsigs                  1.0.2                      py_3    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
gast                      0.2.2                      py_0    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
gmpy2                     2.1.0b1          py27h1744cca_0    conda-forge
grpcio                    1.16.1           py27h044775b_1  
html5lib                  0.9999999                py27_0    conda-forge
icu                       56.1                          4    conda-forge
importlib-metadata        0.18                     pypi_0    pypi
instant                   2016.1.0                 pypi_0    pypi
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         3    conda-forge
libcxxabi                 8.0.0                         3    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libprotobuf               3.8.0                hfbae3c0_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libuv                     1.30.0               h01d97ff_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
mock                      3.0.5                    py27_0    conda-forge
more-itertools            5.0.0                    pypi_0    pypi
mpc                       1.1.0             h3aece09_1006    conda-forge
mpfr                      4.0.2                h0a95893_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.4           py27h6b0580a_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
packaging                 19.0                     pypi_0    pypi
pathlib2                  2.3.4                    pypi_0    pypi
pcre                      8.41              h0a44026_1003    conda-forge
pillow                    6.0.0                    pypi_0    pypi
pip                       19.1.1                   py27_0    conda-forge
pkg-config                0.29.2            h112b980_1005    conda-forge
pluggy                    0.12.0                   pypi_0    pypi
ply                       3.11                       py_1    conda-forge
printind                  4.0                      pypi_0    pypi
protobuf                  3.8.0            py27h6de7cb9_1    conda-forge
py                        1.8.0                    pypi_0    pypi
pyparsing                 2.4.0                    pypi_0    pypi
pytest                    4.6.3                    pypi_0    pypi
python                    2.7.15            h932b40d_1008    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
rhash                     1.3.6             h1de35cc_1001    conda-forge
scandir                   1.10.0                   pypi_0    pypi
scipy                     1.2.2                    pypi_0    pypi
setuptools                41.0.1                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
swig                      4.0.0                h6de7cb9_0    conda-forge
sympy                     1.4                      py27_0    conda-forge
tensorboard               1.8.0                    py27_1    conda-forge
tensorflow                1.8.0                    py27_1    conda-forge
tensorforce               0.4.2                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
ufl                       2016.1.0                 pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.15.4                     py_0    conda-forge
wheel                     0.33.4                   py27_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zipp                      0.5.1                    pypi_0    pypi
zlib                      1.2.11            h1de35cc_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
  active environment : fenicsproject
    active env location : /anaconda2/envs/fenicsproject
            shell level : 2
       user config file : /Users/weizhang/.condarc
 populated config files : /Users/weizhang/.condarc
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda2/pkgs
                          /Users/weizhang/.conda/pkgs
       envs directories : /anaconda2/envs
                          /Users/weizhang/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/2.7.16 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False


```
</details>

**Comment by johannesring** [comment]
The older conda packages of fenics did not have hdf5 support. I think it was added in 2018.1.0, but that version is Python 3 only.

**Comment by waynezw0618** [comment]
thx, I prefer to use old version. how can fix that?
